### ISSUE TITLE
Cannot tag non-plain text files

### ISSUE THREAD

**Issue by dove0822** [318097/file-ops#1]
I love this extension and would like to use it for file management.
It seems that I can only create tags for plain text files like .md etc.
Is this the original design of the extension? Thank you.

**Comment by 318097** [comment]
Hey @dove0822, the original idea was to be able to tag any type of file (.js, .css, etc). I dint quite understand your question. Are you having an issue tagging any file or would you like to tag a directory?
Please clarify. 
Thanks.

**Comment by dove0822** [comment]
Thank you for your reply. I opened a folder which has nested folders inside it, with some pdfs or Excel file.

Parent 
* Folder 1
    * file1.pdf
    * test.md
* Folder 2
    * excel1.xlsx

I click `ctrl shift p` --> `File tag: Create tag` for the pdf and Excel file at the file explorer, then nothing pops up for me to create a tag but it works for the .md file.

**Comment by 318097** [comment]
Hey, it seems to work. Just make sure you open a folder in VS Code. A folder is treated as a workspace and at the root `.file-ops` file is created which stores all the tagged files.

![Screenshot 2021-05-06 at 3 18 14 PM](https://user-images.githubusercontent.com/18000784/117278475-6e9fa280-ae7e-11eb-8def-e4ec7804b1d5.png)
