### ISSUE TITLE
Allow suffix with dots in quickSwitchPairs

### ISSUE THREAD

**Issue by jangxyz** [318097/file-ops#20]
It would be great if `quickSwitchPairs` can accept suffixes including other letters beside `[a-z]`, like dots(`.`)

I am working with SvelteKit and this looks like a great extension to navigate between svelte page components and server files. This is how my typical folder looks like:

```
.
└── nodes
    └── [nodeId]
        ├── +page.server.ts
        ├── +page.ts
        ├── +page.svelte
        ├── +error.svelte
        ├── Node.svelte
        └── idRefs_action.ts  
```
(You can find detailed explanations about svelte kit's directory structure on [Svelte kit document](https://kit.svelte.dev/docs/routing))

My usage is simple: navigate between the `+page*` files.
I tried to set `fileOps.fileSwitch.quickSwitchPairs` as `".svelte/.server.ts,.server.js"`, but it turns out that it is an unaccepted pattern. The extension specifically tests if the input matches the pattern ([extension.ts:L231](https://github.com/318097/file-ops/blob/ba1c6510f28b653d5a601ed0bb55f22cf0321922/src/extension.ts#L213)): 

```javascript
/^(\.[a-z]+)(,(\.[a-z]+))*\/(\.[a-z]+)(,(\.[a-z]+))*$/
```

which translates to briefly:
1) comma separated extension(.[a-z]*)s
2) a slash
3) comma separated extension(.[a-z]*)s 

According to the pattern, `.server.ts` is invalid because it contains a dot.

I can imagine that you particularly had 'extension' in mind, but this can easily meet further extensions, like 'an extension with numbers, or capital letters'.

My direct request is to "make it accept suffixes, not extensions", so I could match `*.server.ts` files. Adding a more elaborate patterns would also be a good idea, like accepting regexes in the first place -- that way I could actually confine to "files that start with `+page.`.

What do you think?

**Comment by 318097** [comment]
@jangxyz - Great improvement. Thanks for the idea. I am working on v3 for the app and will release this fix in that version itself. It will take some time, but expect it by the end of this month.

**Comment by 318097** [comment]
@jangxyz - This has been resolved in `v3`. Hope you like it.
